### ISSUE TITLE
bonsai_scxml_ros requires bonsai_msgs 0.4.1 while only 0.4.0 is provided

### ISSUE THREAD

**Issue by semeyerz** [CentralLabFacilities/bonsai#1]
> [ERROR] Failed to execute goal on project bonsai_scxml_ros: Could not resolve dependencies for project de.unibi.citec.clf:bonsai_scxml_ros:jar:0.5.0: Could not find artifact org.ros.rosjava_messages:bonsai_msgs:jar:0.4.1

**Comment by LeroyR** [comment]
fixed with e19ca13039a561f4f6b4150e0541653d3fc411d2
